import assert from "node:assert/strict";
import test from "node:test";
import { calculateCascadeImpact,canConfirmVisualPrinciple,type PrincipleApproval } from "../lib/domain/projectVisual";
import { ProjectVisualService,ProjectVisualServiceError,type ProjectVisualServiceDependencies } from "../lib/services/projectVisual";

const now="2026-08-02T00:00:00.000Z";
const project={id:"project-1",title:"Breath",domain:"film",status:"development",oneLine:null,createdAt:now,updatedAt:now};
const emptyWorkspace=()=>({project,scenes:[],shots:[],references:[],principles:[],decisionQuestions:[],characterVisuals:[],cascadeImpacts:[],decisionLineage:[]});
function dependencies(overrides:Partial<ProjectVisualServiceDependencies>={}):ProjectVisualServiceDependencies{
  const missing=async()=>{throw new Error("not implemented in test");};
  return{
    readModel:{get:async()=>emptyWorkspace()},
    references:{create:missing,update:missing,get:async()=>null,linkScene:missing},
    questions:{create:missing,get:async()=>null,setState:missing},
    principles:{create:missing,get:async()=>null,appendVersion:missing,setCurrentVersion:missing,linkScenes:missing,linkShots:missing,updateVersion:missing},
    approvals:{recordAndEvaluate:missing,withdrawAndEvaluate:missing,list:async()=>[]},
    characters:{create:missing},lineage:{create:missing},...overrides,
  } as ProjectVisualServiceDependencies;
}

test("workspace_read_model_empty_project",async()=>{const service=new ProjectVisualService(dependencies());const result=await service.getProjectVisualWorkspace("project-1");assert.equal(result.project.id,"project-1");assert.deepEqual(result.references,[]);assert.deepEqual(result.cascadeImpacts,[]);});
test("reference_create_update_read",async()=>{const refs=new Map<string,any>();const repo={create:async(i:any)=>{const r={...i,assetUri:i.assetUri??null,createdAt:now,updatedAt:now};refs.set(i.id,r);return r;},update:async(i:any)=>{const r={...refs.get(i.id),...i};refs.set(i.id,r);return r;},get:async(id:string)=>refs.get(id)??null,linkScene:async()=>{}};const service=new ProjectVisualService(dependencies({references:repo as any}));const input={id:"ref-1",projectId:"project-1",title:"Pool",sourceMethod:"generated",contentType:"world",adoptionLevel:"core" as const,referenceImageState:"uploaded" as const,assetUri:"assets/pool.png",responsibleRole:"director"};await service.createReference(input);await service.updateReference({...input,title:"Pool revised"});assert.equal((await service.getReference("project-1","ref-1")).title,"Pool revised");});
test("decision_question_decided_creates_candidate_not_confirmed",async()=>{let state:any="open";let createdStatus:string|null=null;const service=new ProjectVisualService(dependencies({questions:{create:async()=>({} as any),get:async()=>({id:"q-1",projectId:"project-1",question:"Tone?",context:null,state,priority:0,decidedOption:null,decidedBy:null,decidedAt:null,evidence:[],createdAt:now,updatedAt:now}),setState:async(i:any)=>{state=i.state;return{state,...i};}} as any,principles:{create:async(i:any)=>{createdStatus=i.status;return{...i,currentVersionId:null,createdAt:now,updatedAt:now};},get:async()=>null,appendVersion:async(i:any)=>i,setCurrentVersion:async()=>{},linkScenes:async()=>{},linkShots:async()=>{},updateVersion:async()=>({} as any)} as any,lineage:{create:async(i:any)=>i} as any}));const result=await service.decideQuestion({projectId:"project-1",questionId:"q-1",decidedOption:"blue",decidedBy:"director-1",decidedAt:now,candidate:{principleId:"principle-1",title:"Blue isolation",version:{id:"version-1",principleId:"principle-1",versionNumber:1,principleText:"Blue",rationale:"Tone",sourceQuestionId:"q-1",contentHash:"hash"},lineageId:"lineage-1"}});assert.equal(result.question.state,"decided");assert.equal(createdStatus,"candidate");assert.notEqual(createdStatus,"confirmed");});
function approvalService(){const approvals:PrincipleApproval[]=[];const deps=dependencies({approvals:{recordAndEvaluate:async(i:any)=>{approvals.push({principleVersionId:i.approval.principleVersionId,role:i.approval.role,approverId:i.approval.approverId,approvedAt:now,status:"active"});return canConfirmVisualPrinciple(approvals)?"confirmed":"needs_review";},withdrawAndEvaluate:async(i:any)=>{const found=approvals.find(a=>a.approverId===i.approverId);if(found)found.status="withdrawn";return"needs_review";},list:async()=>approvals as any} as any});return{service:new ProjectVisualService(deps),approvals};}
test("director_only_approval_does_not_confirm",async()=>{const{service}=approvalService();const status=await service.approvePrincipleVersion({projectId:"project-1",principleId:"principle-1",versionId:"version-1",approvalId:"approval-1",approverId:"director-1",role:"director",lineageId:"lineage-1"});assert.equal(status,"needs_review");});
test("director_and_producer_approval_confirms_same_version",async()=>{const{service}=approvalService();await service.approvePrincipleVersion({projectId:"project-1",principleId:"principle-1",versionId:"version-1",approvalId:"approval-1",approverId:"director-1",role:"director",lineageId:"lineage-1"});const status=await service.approvePrincipleVersion({projectId:"project-1",principleId:"principle-1",versionId:"version-1",approvalId:"approval-2",approverId:"producer-1",role:"producer",lineageId:"lineage-2"});assert.equal(status,"confirmed");});
test("withdrawn_approval_moves_principle_to_needs_review",async()=>{const{service}=approvalService();const status=await service.withdrawPrincipleApproval({projectId:"project-1",principleId:"principle-1",versionId:"version-1",approvalId:"approval-1",approverId:"director-1",reason:"Changed",lineageId:"lineage-1"});assert.equal(status,"needs_review");});
function cascadeUpdate(){let impacts:any[]=[];const service=new ProjectVisualService(dependencies({principles:{create:async()=>({} as any),get:async()=>null,appendVersion:async()=>({} as any),setCurrentVersion:async()=>{},linkScenes:async()=>{},linkShots:async()=>{},updateVersion:async(i:any)=>{impacts=calculateCascadeImpact(i.cascadeInput);return i.version;}} as any}));const input:any={projectId:"project-1",version:{id:"version-2",principleId:"principle-1",versionNumber:2,principleText:"x",rationale:"x",contentHash:"h2"},sceneLinks:[],shotLinks:[],cascadeInput:{changeType:"version_update",beforeVersion:null,afterVersion:{id:"version-2",principleId:"principle-1",version:2,status:"candidate",contentHash:"h2"},principleSceneLinks:[],principleShotLinks:[],targets:[{targetType:"scene",targetId:"scene-1",reviewStatus:"current",inExplicitScope:true,legacyLinkAvailable:true},{targetType:"scene",targetId:"scene-2",reviewStatus:"current",inExplicitScope:false,legacyLinkAvailable:true},{targetType:"shot",targetId:"shot-1",shotStatus:"proposed",generatedImageState:"not_generated",inExplicitScope:true,legacyLinkAvailable:true},{targetType:"shot",targetId:"shot-legacy",shotStatus:"approved",generatedImageState:"generated",inExplicitScope:false,legacyLinkAvailable:false}]},impactIdFor:()=>crypto.randomUUID()};return{service,input,getImpacts:()=>impacts};}
test("version_update_persists_all_impact_results",async()=>{const c=cascadeUpdate();await c.service.updateConfirmedPrincipleVersion(c.input);assert.deepEqual(new Set(c.getImpacts().map((i:any)=>i.impactResult)),new Set(["affected","unaffected","unknown"]));});
test("unapproved_linked_shot_remains_proposed",async()=>{const c=cascadeUpdate();await c.service.updateConfirmedPrincipleVersion(c.input);const shot=c.getImpacts().find((i:any)=>i.targetId==="shot-1");assert.equal(shot.impactResult,"affected");assert.equal(shot.targetNewStatus,null);});
test("invalid_state_transition_returns_409",async()=>{const service=new ProjectVisualService(dependencies({questions:{create:async()=>({} as any),get:async()=>({id:"q-1",projectId:"project-1",state:"decided"} as any),setState:async()=>({} as any)}}));await assert.rejects(()=>service.updateDecisionQuestionState({projectId:"project-1",questionId:"q-1",state:"discussion"}),(error:any)=>error instanceof ProjectVisualServiceError&&error.code==="INVALID_STATE_TRANSITION"&&error.status===409);});
