import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,existsSync} from 'node:fs';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {randomUUID,createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
test('team operations — isolated synthetic records, real SQLite and ffmpeg',async t=>{
 const dir=mkdtempSync(path.join(tmpdir(),'nodam-team-'));process.env.SCENENOTE_DB=path.join(dir,'db');
 const {db}=await import('../lib/db');const d=db();const {createIntake}=await import('../lib/meetingIntake/store');
 const {getDecisionBoard,changeDecisionBoard}=await import('../lib/meetingDecisions/store');const {issueParticipantAccess,revokeParticipantAccess,participantView,participantCommand}=await import('../lib/meetingDecisions/access');
 const {startSession,stopSession,resumeSession,ingestChunk}=await import('../lib/live/session');const {segmentBase,segmentSnapshot,meetingSegments,speakerChunkIndex}=await import('../lib/live/segments');
 const {validAdmin,publicParticipantPath}=await import('../lib/teamAccess');
 const create=(mode='text')=>createIntake({requestId:randomUUID(),title:'운영 합성 검증',purpose:'서로 이해한 출시 범위를 확인합니다',kind:'decision',mode,sourceType:'actual',text:mode==='text'?'민지: 빠른 출시가 필요합니다.':''}).meetingId;
 const setup=()=>{const id=create();let b=changeDecisionBoard(id,0,{action:'participant',name:'민지',role:''});b=changeDecisionBoard(id,b.revision,{action:'participant',name:'준호',role:''});b=changeDecisionBoard(id,b.revision,{action:'question',question:'출시 범위는?',evidence:[{uid:'U01',quote:'빠른 출시가 필요합니다.'}]});b=changeDecisionBoard(id,b.revision,{action:'proposal',questionId:b.questions[0].id,proposal:'검색 기능부터 출시',ownerId:b.participants[0].id,dueDate:null,criteria:'검색 동작 확인'});return {id,b};};
 try{
 await t.test('personal invitation records only its own response with audit provenance',()=>{const {id,b}=setup(),p=b.participants[0],invite=issueParticipantAccess(id,p.id);const view=participantView(invite.token);assert.equal(view.participant.id,p.id);assert.equal('history' in view,false);assert.equal('meetingId' in view,false);
  const result=participantCommand(invite.token,b.revision,{action:'response',questionId:b.questions[0].id,stance:'agree',understanding:'검색부터 출시',concern:''});assert.equal(result.questions[0].response?.participantId,p.id);assert.equal(result.questions[0].response?.recordedVia,'personal_link');const saved=getDecisionBoard(id);assert.match((saved.history[0] as any).detail_json,/participant_invite_holder/);assert.equal(saved.questions[0].confirmedAt,null);
  assert.throws(()=>participantCommand(invite.token,saved.revision,{action:'confirm',questionId:b.questions[0].id}),/본인의 해석/);
  assert.throws(()=>participantCommand(invite.token,saved.revision,{action:'response',participantId:b.participants[1].id,questionId:b.questions[0].id,stance:'agree',understanding:'위조'}),/다른 참가자/);
  const other=setup();assert.throws(()=>participantCommand(invite.token,saved.revision,{action:'response',questionId:other.b.questions[0].id,stance:'agree',understanding:'다른 회의'}),/이 회의의 안건/);
  assert.throws(()=>participantCommand(invite.token,b.revision,{action:'response',questionId:b.questions[0].id,stance:'agree',understanding:'오래된 버전'}),/다른 변경/);
 });
 await t.test('expiry, revocation, rotation and invalid token deny access; DB stores hashes only',()=>{const {id,b}=setup(),p=b.participants[0].id,a=issueParticipantAccess(id,p);assert.throws(()=>participantView('bad'),/초대 링크/);const b2=issueParticipantAccess(id,p);assert.throws(()=>participantView(a.token),/회수/);assert.ok(participantView(b2.token));const rows=d.prepare('SELECT * FROM participant_access').all();assert.ok(!JSON.stringify(rows).includes(b2.token));revokeParticipantAccess(id,p);assert.throws(()=>participantView(b2.token),/회수/);const c=issueParticipantAccess(id,p);d.prepare('UPDATE participant_access SET expires_at=0 WHERE participant_id=?').run(p);assert.throws(()=>participantView(c.token),/만료/);});
 await t.test('management password and public path allowlist fail closed',()=>{const password='synthetic-strong-random-password',h=createHash('sha256').update(password).digest('hex'),auth='Basic '+Buffer.from('admin:'+password).toString('base64');assert.equal(validAdmin(auth,h),true);assert.equal(validAdmin(auth,undefined),false);assert.equal(validAdmin('Basic '+Buffer.from('admin:wrong').toString('base64'),h),false);assert.equal(publicParticipantPath('/api/participation'),true);for(const p of ['/api/meetings/x/decisions','/v2','/api/participation/../meetings','/join/other'])assert.equal(publicParticipantPath(p),false);});
 await t.test('same meeting continues with new segment; old snapshot stays unchanged after restart',async()=>{const id=create('live'),opts={facilitator:{goal:'서로 이해한 출시 범위를 확인합니다',intervalMinutes:3 as const}},first=startSession(id,'mic',opts);
  const wav=path.join(dir,'tone.wav');execFileSync('ffmpeg',['-v','error','-f','lavfi','-i','sine=frequency=440:sample_rate=16000','-t','1',wav]);
  d.prepare("INSERT INTO live_chunks(session_id,idx,offset_ms,duration_ms,file_path,status,created_at)VALUES(?,0,0,1000,?,'done','now')").run(first.sessionId,wav);first.mediaEndMs=1000;
  assert.throws(()=>startSession(id,'mic',{...opts,continueMeeting:true}),/이미 라이브|복구/);await stopSession(first.sessionId);const before=segmentSnapshot(id,first.sessionId)!.snapshot_json;assert.ok(before);
  const second=startSession(id,'mic',{...opts,continueMeeting:true});assert.notEqual(second.sessionId,first.sessionId);assert.equal(segmentBase(second.sessionId),1000);assert.equal(speakerChunkIndex(second.sessionId,0),1);assert.equal(second.mediaEndMs,1000);assert.throws(()=>ingestChunk(second.sessionId,{bytes:Buffer.from('bad'),ext:'wav',offsetMs:0}),/앞선 시각/);
  (globalThis as any).__scenenoteLive.delete(second.sessionId);const recovered=resumeSession(id,second.sessionId);await recovered.queue;assert.equal(recovered.mediaEndMs,1000);await stopSession(second.sessionId);assert.equal(segmentSnapshot(id,first.sessionId)!.snapshot_json,before);assert.equal(meetingSegments(id).length,2);assert.ok(segmentSnapshot(id,second.sessionId)!.snapshot_json);assert.equal(segmentSnapshot(create(),first.sessionId),undefined);const {POST:finalize}=await import('../app/api/meetings/[id]/live/finalize/route');assert.equal((await finalize(new Request('http://local',{method:'POST',body:'{}'}),{params:Promise.resolve({id})})).status,409);
 });
 await t.test('backup can restore an independently readable SQLite database',()=>{const target=path.join(dir,'backup.db');execFileSync(process.execPath,['scripts/backup-meeting-db.mjs',target],{env:process.env});assert.ok(existsSync(target));const {DatabaseSync}=require('node:sqlite');const restored=new DatabaseSync(target,{readOnly:true});assert.equal(restored.prepare('PRAGMA integrity_check').get().integrity_check,'ok');assert.equal(restored.prepare('SELECT COUNT(*) n FROM meetings').get().n,(d.prepare('SELECT COUNT(*) n FROM meetings').get() as any).n);restored.close();assert.throws(()=>execFileSync(process.execPath,['scripts/backup-meeting-db.mjs',target],{env:process.env,stdio:'pipe'}));});
 }finally{d.close();}
});
