import {test} from "node:test";
import assert from "node:assert/strict";
import {mkdtempSync,rmSync} from "node:fs";
import {tmpdir} from "node:os";
import path from "node:path";
import {randomUUID} from "node:crypto";
test("v2 recovery, source edits and separate recording end — synthetic DB",async t=>{
 const dir=mkdtempSync(path.join(tmpdir(),"nodam-recovery-"));process.env.SCENENOTE_DB=path.join(dir,"db");
 const {db}=await import("../lib/db");const {createIntake}=await import("../lib/meetingIntake/store");
 const {getMeetingUtterances,createRun,finishRun}=await import("../lib/alignment/store");
 const {beginAnalysisJob,recoverAnalysisJobs,renewAnalysisJob,assertAnalysisJob,analysisSourceChanged}=await import("../lib/alignment/jobs");
 const {editUtterance}=await import("../lib/meetingIntake/edit");
 const {startSession,stopSession}=await import("../lib/live/session");const {POST:stop}=await import("../app/api/meetings/[id]/live/stop/route");
 const d=db();const meeting=(mode="text")=>createIntake({requestId:randomUUID(),title:"합성 복구 검증",purpose:"회수와 원문 변경을 검증합니다",kind:"discussion",mode,sourceType:"actual",text:mode==="text"?"가: 빠른 출시를 원합니다.\n나: 기능을 줄이자는 뜻인가요?":""}).meetingId;
 try{
 await t.test("heartbeat protects an active job; expired job can retry; old owner cannot publish",()=>{const id=meeting(),source=getMeetingUtterances(id),a=beginAnalysisJob(id,"synthetic",null,source);assert.equal(renewAnalysisJob(a),true);assert.equal(recoverAnalysisJobs(id),0);assert.throws(()=>beginAnalysisJob(id,"synthetic",null,source),/이미 전체 분석/);d.prepare("UPDATE analysis_jobs SET expires_ms=0 WHERE run_id=?").run(a);assert.equal(recoverAnalysisJobs(id),1);assert.equal(renewAnalysisJob(a),false);assert.throws(()=>assertAnalysisJob(a),/만료/);const b=beginAnalysisJob(id,"synthetic",null,source);assert.notEqual(a,b);assertAnalysisJob(b);});
 await t.test("legacy abandoned run is recovered without touching recent legacy work",()=>{const id=meeting(),a=createRun(id,"batch","legacy");assert.equal(recoverAnalysisJobs(id),0);d.prepare("UPDATE alignment_v2_runs SET created_at='2000-01-01' WHERE id=?").run(a);assert.equal(recoverAnalysisJobs(id),1);assert.equal((d.prepare("SELECT status FROM alignment_v2_runs WHERE id=?").get(a) as any).status,"failed");});
 await t.test("new speech does not alter snapshot; edited names/text do, original and audit survive",()=>{const id=meeting(),source=getMeetingUtterances(id),a=beginAnalysisJob(id,"synthetic",null,source);finishRun(a,{status:"completed"});d.prepare("INSERT INTO utterances(id,meeting_id,idx,uid,text_clean,text_raw,created_at)VALUES(?,?,2,'U03','이후 발언','이후 발언','now')").run(randomUUID(),id);assert.equal(analysisSourceChanged(a,id),false);const u=source[0];editUtterance(id,{uid:u.uid,text:"기능을 줄여 빠르게 출시합니다.",speakerName:"민지",expectedText:u.text,expectedSpeakerName:u.speakerName});assert.equal(analysisSourceChanged(a,id),true);assert.equal(getMeetingUtterances(id)[0].speakerKey,"N:민지");assert.equal((d.prepare("SELECT text_raw FROM utterances WHERE meeting_id=? AND uid=?").get(id,u.uid) as any).text_raw,u.text);assert.equal((d.prepare("SELECT COUNT(*) n FROM utterance_edits WHERE meeting_id=?").get(id) as any).n,1);assert.throws(()=>editUtterance(id,{uid:u.uid,text:u.text,speakerName:"나",expectedText:u.text,expectedSpeakerName:u.speakerName}),/다른 수정/);});
 await t.test("source editing rejects wrong meeting and active recording",()=>{const id=meeting(),u=getMeetingUtterances(id)[0],input={uid:u.uid,text:u.text,speakerName:"나",expectedText:u.text,expectedSpeakerName:u.speakerName};assert.throws(()=>editUtterance("missing",input),/발언을 찾을/);const run=createRun(id,"live","synthetic");d.prepare("INSERT INTO live_sessions(id,meeting_id,run_id,mode,status,started_at)VALUES(?,?,?,'mic','recording','now')").run(randomUUID(),id,run);assert.throws(()=>editUtterance(id,input),/종료 처리가 끝난/);assert.equal(getMeetingUtterances(id)[0].speakerName,u.speakerName);});
 await t.test("recording end is persisted before pending processing finishes",async()=>{const id=meeting("live"),e=startSession(id,"mic",{facilitator:{goal:"음성 종료 시점과 처리를 구분합니다",intervalMinutes:3}});let release!:()=>void;e.queue=new Promise<void>(r=>release=r);const pending=stopSession(e.sessionId);const before=d.prepare("SELECT status,stopped_at FROM live_sessions WHERE id=?").get(e.sessionId) as any;assert.equal(before.status,"stopping");assert.ok(before.stopped_at);release();await pending;const after=d.prepare("SELECT status,stopped_at FROM live_sessions WHERE id=?").get(e.sessionId) as any;assert.equal(after.status,"stopped");assert.equal(after.stopped_at,before.stopped_at);});
 await t.test("interrupted finish can recover without reopening microphone; repeat stop is idempotent",async()=>{const id=meeting("live"),e=startSession(id,"mic",{facilitator:{goal:"중단된 종료 처리만 복구합니다",intervalMinutes:3}});d.prepare("UPDATE live_sessions SET status='stopping',stopped_at='2026-09-28T00:00:00Z' WHERE id=?").run(e.sessionId);(globalThis as any).__scenenoteLive.delete(e.sessionId);for(let n=0;n<2;n++){const r=await stop(new Request("http://localhost/stop",{method:"POST",body:JSON.stringify({sessionId:e.sessionId})}),{params:Promise.resolve({id})});assert.equal(r.status,200);}assert.equal((d.prepare("SELECT stopped_at FROM live_sessions WHERE id=?").get(e.sessionId) as any).stopped_at,"2026-09-28T00:00:00Z");});

 await t.test("editing legacy analysis without a snapshot also marks it stale",()=>{const id=meeting(),run=createRun(id,"batch","legacy");finishRun(run,{status:"completed"});const u=getMeetingUtterances(id)[0];assert.equal(analysisSourceChanged(run,id),false);editUtterance(id,{uid:u.uid,text:u.text,speakerName:"수정 화자",expectedText:u.text,expectedSpeakerName:u.speakerName});assert.equal(analysisSourceChanged(run,id),true);});
 await t.test("postprocessing exception leaves recording ended and finish retryable",async()=>{const id=meeting("live"),e=startSession(id,"mic",{facilitator:{goal:"후처리 예외를 복구합니다",intervalMinutes:3}});e.queue=Promise.reject(new Error("synthetic postprocessing failure"));void e.queue.catch(()=>{});const req=()=>new Request("http://local/stop",{method:"POST",body:JSON.stringify({sessionId:e.sessionId})});const r=await stop(req(),{params:Promise.resolve({id})});assert.equal(r.status,502);assert.equal(e.stopping,false);const row=d.prepare("SELECT stopped_at FROM live_sessions WHERE id=?").get(e.sessionId) as any;assert.ok(row.stopped_at);assert.equal((await stop(req(),{params:Promise.resolve({id})})).status,200);assert.equal((d.prepare("SELECT stopped_at FROM live_sessions WHERE id=?").get(e.sessionId) as any).stopped_at,row.stopped_at);});
 }finally{d.close();rmSync(dir,{recursive:true,force:true});}
});
