"use client";
import {useEffect,useState} from "react";
import type {participantView} from "@/lib/meetingDecisions/access";
import s from "../v2/v2.module.css";
type View=ReturnType<typeof participantView>;
export default function Join(){
 const [data,setData]=useState<View|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 async function load(){try{const token=location.hash.slice(1);if(token){sessionStorage.setItem("nodam-participant",token);history.replaceState(null,"",location.pathname);}const r=await fetch("/api/participation",{headers:{authorization:`Bearer ${sessionStorage.getItem("nodam-participant")??""}`},cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j.error);setData(j);setError("");}catch(e){setError((e as Error).message);}}
 useEffect(()=>{void load();},[]);
 async function send(command:unknown){if(!data||busy)return;setBusy(true);setError("");try{const r=await fetch("/api/participation",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${sessionStorage.getItem("nodam-participant")??""}`},body:JSON.stringify({revision:data.revision,command})});const j=await r.json();if(!r.ok){if(r.status===409)await load();throw new Error(j.error);}setData(j);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <main className={s.page}><div className={s.wrap}><h1>동상이몽 · 내 생각 확인</h1><p className={s.notice}>본인에게 전달된 개인 링크로 응답하세요. 링크를 공유하면 다른 사람이 대신 응답할 수 있습니다. 실명 인증된 투표는 아닙니다.</p>{error&&<p role="alert" className={s.notice}>{error}</p>}<button onClick={()=>void load()} disabled={busy}>최신 안건 불러오기</button>{data&&<><h2>{data.participant.name} 님</h2><p>{data.goal}</p>{!data.questions.length&&<p>진행자가 안건을 등록하면 여기에 표시됩니다.</p>}{data.questions.map(q=><section className={`${s.card} ${s.section}`} key={q.id}><h2>{q.question}</h2>{q.evidence.map(e=><p key={e.uid}>{e.uid} “{e.quote}”</p>)}{q.sourceChanged&&<p role="alert">근거가 바뀌어 진행자의 재검토가 필요합니다.</p>}{q.confirmedAt?<p>확인 완료 · {q.proposal}</p>:<>
 {q.comparison&&<form className={s.form} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void send({action:"interpretation",questionId:q.id,meaning:f.get("meaning"),example:f.get("example"),conditions:f.get("conditions"),confirmedByParticipant:true});}}><h3>“{q.comparison.expression}”의 내 뜻</h3><label>내가 이해한 뜻<textarea name="meaning" required maxLength={1000} defaultValue={q.comparison.interpretations.find(i=>i.participantId===data.participant.id)?.meaning??""}/></label><label>구체적인 예<textarea name="example" maxLength={1000} defaultValue={q.comparison.interpretations.find(i=>i.participantId===data.participant.id)?.example??""}/></label><label>꼭 지켜야 할 조건<textarea name="conditions" maxLength={1000} defaultValue={q.comparison.interpretations.find(i=>i.participantId===data.participant.id)?.conditions??""}/></label><button disabled={busy||q.sourceChanged}>내 해석 저장</button></form>}
 {q.proposal?<form className={s.form} key={q.proposal} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void send({action:"response",questionId:q.id,stance:f.get("stance"),understanding:f.get("understanding"),concern:f.get("concern")});}}><h3>결정안</h3><p>{q.proposal}</p><label>내 의견<select name="stance" defaultValue={q.response?.stance??"uncertain"}><option value="uncertain">판단 보류</option><option value="agree">진행 동의</option><option value="agree_with_concerns">우려를 남기고 동의</option><option value="disagree">추가 논의 요청</option></select></label><label>내가 이해한 결정<textarea name="understanding" required maxLength={1000} defaultValue={q.response?.understanding??""}/></label><label>우려·남은 질문<textarea name="concern" maxLength={1000} defaultValue={q.response?.concern??""}/></label><button disabled={busy||q.sourceChanged}>내 응답 저장</button>{q.response&&<p role="status">내 응답이 저장되어 있습니다.</p>}</form>:<p>결정안이 작성되면 동의 여부를 남길 수 있습니다.</p>}
 </>}</section>)}</>}</div></main>;
}
