import { defaultProjectVisualAdapter,type CascadeInput,type DecisionQuestionState,type VisualPrincipleStatus } from "../../domain/projectVisual";
import type { ApprovalRepository,CharacterVisualRepository,DecisionLineageRepository,DecisionQuestionRepository,PrincipleRepository,ProjectVisualWorkspaceReadModel,ReferenceRepository,WorkspaceReadModelRepository } from "../../repositories/projectVisual";
import type { CharacterVisualWrite,PrincipleVersionUpdate,PrincipleVersionWrite,ReferenceWrite } from "../../repositories/projectVisual";
import { ProjectVisualServiceError } from "./errors";
import { asset,choice,id,positiveInteger,questionState,role,text,timestamp } from "./validation";

export type ProjectVisualServiceDependencies={
  readModel:Pick<WorkspaceReadModelRepository,"get">;
  references:Pick<ReferenceRepository,"create"|"update"|"get"|"linkScene">;
  questions:Pick<DecisionQuestionRepository,"create"|"get"|"setState">;
  principles:Pick<PrincipleRepository,"create"|"get"|"appendVersion"|"setCurrentVersion"|"linkScenes"|"linkShots"|"updateVersion">;
  approvals:Pick<ApprovalRepository,"recordAndEvaluate"|"withdrawAndEvaluate"|"list">;
  characters:Pick<CharacterVisualRepository,"create">;
  lineage:Pick<DecisionLineageRepository,"create">;
};
const TRANSITIONS:Record<DecisionQuestionState,DecisionQuestionState[]>={open:["discussion","decision_proposed","decided"],discussion:["decision_proposed","decided"],decision_proposed:["discussion","decided"],decided:["reopened"],reopened:["discussion","decision_proposed","decided"]};
export class ProjectVisualService{
  constructor(private readonly deps:ProjectVisualServiceDependencies){}
  async getProjectVisualWorkspace(projectId:string):Promise<ProjectVisualWorkspaceReadModel>{const result=await this.deps.readModel.get(id(projectId,"projectId"));if(!result)throw new ProjectVisualServiceError("NOT_FOUND","Project was not found");return result;}
  async createReference(input:ReferenceWrite){id(input.id,"referenceId");id(input.projectId,"projectId");text(input.title,"title");text(input.sourceMethod,"sourceMethod");text(input.contentType,"contentType");choice(input.adoptionLevel,["core","support","candidate","exclude"] as const,"adoptionLevel");choice(input.referenceImageState,["not_uploaded","uploaded"] as const,"referenceImageState");text(input.responsibleRole,"responsibleRole");input.assetUri=asset(input.assetUri);if(input.referenceImageState==="uploaded"&&!input.assetUri)throw new ProjectVisualServiceError("VALIDATION_ERROR","assetUri is required when referenceImageState is uploaded");return this.deps.references.create(input);}
  async updateReference(input:ReferenceWrite){id(input.id,"referenceId");id(input.projectId,"projectId");text(input.title,"title");text(input.sourceMethod,"sourceMethod");text(input.contentType,"contentType");choice(input.adoptionLevel,["core","support","candidate","exclude"] as const,"adoptionLevel");choice(input.referenceImageState,["not_uploaded","uploaded"] as const,"referenceImageState");text(input.responsibleRole,"responsibleRole");input.assetUri=asset(input.assetUri);if(input.referenceImageState==="uploaded"&&!input.assetUri)throw new ProjectVisualServiceError("VALIDATION_ERROR","assetUri is required when referenceImageState is uploaded");const current=await this.deps.references.get(input.id);if(!current||current.projectId!==input.projectId)throw new ProjectVisualServiceError("NOT_FOUND","Reference was not found");return this.deps.references.update(input);}
  async getReference(projectId:string,referenceId:string){id(projectId,"projectId");id(referenceId,"referenceId");const result=await this.deps.references.get(referenceId);if(!result||result.projectId!==projectId)throw new ProjectVisualServiceError("NOT_FOUND","Reference was not found");return result;}
  async listReferences(projectId:string){return(await this.getProjectVisualWorkspace(projectId)).references;}
  async linkReferenceToScene(projectId:string,referenceId:string,sceneId:string){const workspace=await this.getProjectVisualWorkspace(projectId);if(!workspace.references.some(r=>r.id===id(referenceId,"referenceId")))throw new ProjectVisualServiceError("NOT_FOUND","Reference was not found");if(!workspace.scenes.some(s=>s.id===id(sceneId,"sceneId")))throw new ProjectVisualServiceError("NOT_FOUND","Scene was not found");await this.deps.references.linkScene(referenceId,sceneId);return{referenceId,sceneId};}
  async createDecisionQuestion(input:{id:string;projectId:string;question:string;context?:string|null;priority?:number;evidence?:unknown[]}){id(input.id,"questionId");id(input.projectId,"projectId");text(input.question,"question");if(input.priority!==undefined&&!Number.isInteger(input.priority))throw new ProjectVisualServiceError("VALIDATION_ERROR","priority must be an integer");return this.deps.questions.create({...input,state:"open"});}
  async listDecisionQuestions(projectId:string){return(await this.getProjectVisualWorkspace(projectId)).decisionQuestions;}
  async updateDecisionQuestionState(input:{projectId:string;questionId:string;state:DecisionQuestionState}){id(input.projectId,"projectId");id(input.questionId,"questionId");const current=await this.deps.questions.get(input.questionId);if(!current||current.projectId!==input.projectId)throw new ProjectVisualServiceError("NOT_FOUND","Decision question was not found");const next=questionState(input.state);if(!TRANSITIONS[current.state].includes(next))throw new ProjectVisualServiceError("INVALID_STATE_TRANSITION",`Cannot move decision question from ${current.state} to ${next}`);return this.deps.questions.setState({id:input.questionId,state:next});}
  async decideQuestion(input:{projectId:string;questionId:string;decidedOption:string;decidedBy:string;decidedAt:string;candidate?:{principleId:string;title:string;version:PrincipleVersionWrite;lineageId:string}}){id(input.projectId,"projectId");id(input.questionId,"questionId");id(input.decidedBy,"decidedBy");text(input.decidedOption,"decidedOption");input.decidedAt=timestamp(input.decidedAt,"decidedAt");const current=await this.deps.questions.get(input.questionId);if(!current||current.projectId!==input.projectId)throw new ProjectVisualServiceError("NOT_FOUND","Decision question was not found");if(!TRANSITIONS[current.state].includes("decided"))throw new ProjectVisualServiceError("INVALID_STATE_TRANSITION",`Cannot decide a question in ${current.state}`);const decided={...current,state:"decided" as const,decidedOptionId:input.decidedOption,decidedBy:input.decidedBy,decidedAt:input.decidedAt};const targetStatus=defaultProjectVisualAdapter.decideQuestion(decided);if(targetStatus!=="candidate")throw new ProjectVisualServiceError("INVALID_STATE_TRANSITION","Decision metadata is incomplete");let candidate=null;if(input.candidate){id(input.candidate.principleId,"principleId");id(input.candidate.version.id,"candidateVersionId");positiveInteger(input.candidate.version.versionNumber,"candidateVersionNumber");text(input.candidate.version.principleText,"candidatePrincipleText");text(input.candidate.version.rationale,"candidateRationale");text(input.candidate.version.contentHash,"candidateContentHash");id(input.candidate.lineageId,"lineageId");if(input.candidate.version.principleId!==input.candidate.principleId||input.candidate.version.sourceQuestionId!==input.questionId)throw new ProjectVisualServiceError("VALIDATION_ERROR","Candidate version must reference the decided question");}const question=await this.deps.questions.setState({id:input.questionId,state:"decided",decidedOption:input.decidedOption,decidedBy:input.decidedBy,decidedAt:input.decidedAt});if(input.candidate){candidate=await this.deps.principles.create({id:input.candidate.principleId,projectId:input.projectId,title:text(input.candidate.title,"title"),status:"candidate"});await this.deps.principles.appendVersion(input.candidate.version);await this.deps.principles.setCurrentVersion(candidate.id,input.candidate.version.id);await this.deps.lineage.create({id:input.candidate.lineageId,projectId:input.projectId,sourceType:"decision_question",sourceId:input.questionId,relation:"decided_into",targetType:"principle_version",targetId:input.candidate.version.id});}return{question,candidate};}
  async createVisualPrinciple(input:{id:string;projectId:string;title:string}){id(input.id,"principleId");id(input.projectId,"projectId");return this.deps.principles.create({...input,title:text(input.title,"title"),status:"candidate"});}
  async createPrincipleVersion(projectId:string,input:PrincipleVersionWrite){id(projectId,"projectId");id(input.id,"versionId");id(input.principleId,"principleId");positiveInteger(input.versionNumber,"versionNumber");text(input.principleText,"principleText");text(input.rationale,"rationale");text(input.contentHash,"contentHash");const principle=await this.deps.principles.get(input.principleId);if(!principle||principle.projectId!==projectId)throw new ProjectVisualServiceError("NOT_FOUND","Visual principle was not found");const version=await this.deps.principles.appendVersion(input);await this.deps.principles.setCurrentVersion(input.principleId,input.id);return version;}
  async linkPrincipleVersionToScenes(projectId:string,versionId:string,links:Array<{sceneId:string;reason:string;evidence?:unknown[]}>){id(projectId,"projectId");id(versionId,"versionId");if(!Array.isArray(links))throw new ProjectVisualServiceError("VALIDATION_ERROR","sceneLinks must be an array");links.forEach(l=>{id(l.sceneId,"sceneId");text(l.reason,"link reason");});await this.deps.principles.linkScenes(versionId,links);return{versionId,sceneIds:links.map(l=>l.sceneId)};}
  async linkPrincipleVersionToShots(projectId:string,versionId:string,links:Array<{shotId:string;reason:string;evidence?:unknown[]}>){id(projectId,"projectId");id(versionId,"versionId");if(!Array.isArray(links))throw new ProjectVisualServiceError("VALIDATION_ERROR","shotLinks must be an array");links.forEach(l=>{id(l.shotId,"shotId");text(l.reason,"link reason");});await this.deps.principles.linkShots(versionId,links);return{versionId,shotIds:links.map(l=>l.shotId)};}
  async getVisualPrinciple(projectId:string,principleId:string){const principle=await this.deps.principles.get(id(principleId,"principleId"));if(!principle||principle.projectId!==id(projectId,"projectId"))throw new ProjectVisualServiceError("NOT_FOUND","Visual principle was not found");return principle;}
  async listVisualPrinciples(projectId:string){return(await this.getProjectVisualWorkspace(projectId)).principles;}
  async approvePrincipleVersion(input:{projectId:string;principleId:string;versionId:string;approvalId:string;approverId:string;role:"director"|"producer";evidenceUid?:string|null;lineageId:string}){id(input.projectId,"projectId");id(input.principleId,"principleId");id(input.versionId,"versionId");id(input.approvalId,"approvalId");id(input.approverId,"approverId");role(input.role);return this.deps.approvals.recordAndEvaluate({approval:{id:input.approvalId,principleVersionId:input.versionId,approverId:input.approverId,role:input.role,evidenceUid:input.evidenceUid},principleId:input.principleId,projectId:input.projectId,lineageId:input.lineageId});}
  async withdrawPrincipleApproval(input:{projectId:string;principleId:string;versionId:string;approvalId:string;approverId:string;reason:string;lineageId:string}){text(input.reason,"reason");return this.deps.approvals.withdrawAndEvaluate({approvalId:id(input.approvalId,"approvalId"),approverId:id(input.approverId,"approverId"),principleId:id(input.principleId,"principleId"),principleVersionId:id(input.versionId,"versionId"),projectId:id(input.projectId,"projectId"),reason:input.reason,lineageId:id(input.lineageId,"lineageId")});}
  listPrincipleApprovals(versionId:string){return this.deps.approvals.list(id(versionId,"versionId"));}
  updateConfirmedPrincipleVersion(input:PrincipleVersionUpdate){if(!input||!input.version||!input.cascadeInput||!Array.isArray(input.sceneLinks)||!Array.isArray(input.shotLinks))throw new ProjectVisualServiceError("VALIDATION_ERROR","Version update payload is incomplete");id(input.projectId,"projectId");id(input.version.id,"versionId");id(input.version.principleId,"principleId");positiveInteger(input.version.versionNumber,"versionNumber");choice(input.cascadeInput.changeType,["first_confirmation","version_update"] as const,"changeType");if(!Array.isArray(input.cascadeInput.targets))throw new ProjectVisualServiceError("VALIDATION_ERROR","cascade targets must be an array");for(const target of input.cascadeInput.targets){id(target.targetId,"targetId");choice(target.targetType,["scene","shot"] as const,"targetType");if(target.targetType==="shot")choice(target.shotStatus,["proposed","approved","restale"] as const,"shotStatus");}return this.deps.principles.updateVersion(input);}
  async createCharacterVisual(input:CharacterVisualWrite){id(input.id,"characterVisualVersionId");id(input.projectId,"projectId");id(input.characterId,"characterId");text(input.characterName,"characterName");positiveInteger(input.versionNumber,"versionNumber");if(input.status)choice(input.status,["candidate","needs_review","confirmed","stale"] as const,"character visual status");input.faceAssetUri=asset(input.faceAssetUri);input.costumeAssetUri=asset(input.costumeAssetUri);input.fullbodyAssetUri=asset(input.fullbodyAssetUri);input.inspaceAssetUri=asset(input.inspaceAssetUri);input.propAssetUri=asset(input.propAssetUri);return this.deps.characters.create(input);}
  async listCharacterVisuals(projectId:string){return(await this.getProjectVisualWorkspace(projectId)).characterVisuals;}
  async listCascadeImpacts(projectId:string,principleId?:string){const workspace=await this.getProjectVisualWorkspace(projectId);if(!principleId)return workspace.cascadeImpacts;id(principleId,"principleId");const versionIds=new Set(workspace.principles.filter(p=>p.id===principleId).map(p=>p.currentVersion?.id).filter(Boolean));return workspace.cascadeImpacts.filter(i=>versionIds.has(i.principleVersionId));}
}
