import { canConfirmVisualPrinciple,statusAfterApprovalWithdrawal,type PrincipleApproval,type VisualPrincipleStatus } from "../../domain/projectVisual";
import type { QueryExecutor,TransactionExecutor } from "./db";
import { DecisionLineageRepository } from "./decisionLineageRepository";
import { toIsoString,type PrincipleApprovalRecord,type TimestampValue } from "./types";
type Row={id:string;principle_version_id:string;approver_id:string;role:"director"|"producer";status:"active"|"withdrawn";evidence_uid:string|null;approved_at:TimestampValue;withdrawn_at:TimestampValue|null;withdrawal_reason:string|null;created_at:TimestampValue};
const map=(r:Row):PrincipleApprovalRecord=>({id:r.id,principleVersionId:r.principle_version_id,approverId:r.approver_id,role:r.role,status:r.status,evidenceUid:r.evidence_uid,approvedAt:toIsoString(r.approved_at)!,withdrawnAt:toIsoString(r.withdrawn_at),withdrawalReason:r.withdrawal_reason,createdAt:toIsoString(r.created_at)!});
const asDomain=(r:PrincipleApprovalRecord):PrincipleApproval=>({principleVersionId:r.principleVersionId,role:r.role,approverId:r.approverId,approvedAt:r.approvedAt,status:r.status});
async function listForVersion(db:QueryExecutor,versionId:string,activeOnly=false):Promise<PrincipleApprovalRecord[]>{const rows=await db.query<Row>(`SELECT * FROM visual_principle_approvals WHERE principle_version_id=$1${activeOnly?" AND status='active'":""} ORDER BY approved_at,id`,[versionId]);return rows.map(map);}
export class ApprovalRepository{
  constructor(private readonly db:TransactionExecutor){}
  async add(i:{id:string;principleVersionId:string;approverId:string;role:"director"|"producer";evidenceUid?:string|null;approvedAt?:string}):Promise<PrincipleApprovalRecord>{const[r]=await this.db.query<Row>("INSERT INTO visual_principle_approvals (id,principle_version_id,approver_id,role,evidence_uid,approved_at) VALUES ($1,$2,$3,$4,$5,COALESCE($6::timestamptz,now())) RETURNING *",[i.id,i.principleVersionId,i.approverId,i.role,i.evidenceUid??null,i.approvedAt??null]);return map(r);}
  list(versionId:string):Promise<PrincipleApprovalRecord[]>{return listForVersion(this.db,versionId);}
  listActive(versionId:string):Promise<PrincipleApprovalRecord[]>{return listForVersion(this.db,versionId,true);}
  async withdraw(id:string,reason:string):Promise<PrincipleApprovalRecord>{const[r]=await this.db.query<Row>("UPDATE visual_principle_approvals SET status='withdrawn',withdrawn_at=now(),withdrawal_reason=$2 WHERE id=$1 AND status='active' RETURNING *",[id,reason]);if(!r)throw new Error(`Active approval not found: ${id}`);return map(r);}
  async recordAndEvaluate(i:{approval:{id:string;principleVersionId:string;approverId:string;role:"director"|"producer";evidenceUid?:string|null};principleId:string;projectId:string;lineageId:string}):Promise<VisualPrincipleStatus>{return this.db.transaction(async tx=>{await new ApprovalRepository({query:tx.query.bind(tx),transaction:async work=>work(tx)}).add(i.approval);const approvals=await listForVersion(tx,i.approval.principleVersionId,true);const status:VisualPrincipleStatus=canConfirmVisualPrinciple(approvals.map(asDomain))?"confirmed":"needs_review";await tx.query("UPDATE visual_principles SET status=$2,updated_at=now() WHERE id=$1",[i.principleId,status]);await new DecisionLineageRepository(tx).create({id:i.lineageId,projectId:i.projectId,sourceType:"approval",sourceId:i.approval.id,relation:"evaluated_for",targetType:"principle_version",targetId:i.approval.principleVersionId,evidenceUid:i.approval.evidenceUid});return status;});}
  async withdrawAndEvaluate(i:{approvalId:string;approverId:string;principleId:string;principleVersionId:string;projectId:string;reason:string;lineageId:string}):Promise<VisualPrincipleStatus>{return this.db.transaction(async tx=>{const before=await listForVersion(tx,i.principleVersionId);const[p]=await tx.query<{status:VisualPrincipleStatus}>("SELECT status FROM visual_principles WHERE id=$1",[i.principleId]);if(!p)throw new Error(`Principle not found: ${i.principleId}`);const[r]=await tx.query<Row>("UPDATE visual_principle_approvals SET status='withdrawn',withdrawn_at=now(),withdrawal_reason=$2 WHERE id=$1 AND status='active' RETURNING *",[i.approvalId,i.reason]);if(!r)throw new Error(`Active approval not found: ${i.approvalId}`);const status=statusAfterApprovalWithdrawal(p.status,before.map(asDomain),i.approverId);await tx.query("UPDATE visual_principles SET status=$2,updated_at=now() WHERE id=$1",[i.principleId,status]);await new DecisionLineageRepository(tx).create({id:i.lineageId,projectId:i.projectId,sourceType:"approval",sourceId:i.approvalId,relation:"withdrawn_from",targetType:"principle_version",targetId:i.principleVersionId});return status;});}
}
