import type { VisualPrincipleStatus } from "../../domain/projectVisual";
import type { QueryExecutor } from "./db";
import { toIsoString,type CharacterVisualRecord,type TimestampValue } from "./types";
type Row={id:string;project_id:string;character_id:string;character_name:string;version_number:number;status:VisualPrincipleStatus;face_asset_uri:string|null;costume_asset_uri:string|null;fullbody_asset_uri:string|null;inspace_asset_uri:string|null;prop_asset_uri:string|null;continuity_lock_json:Record<string,unknown>;allowed_json:unknown[];prohibited_json:unknown[];evidence_json:unknown[];approved_by:string|null;approved_at:TimestampValue|null;created_at:TimestampValue;updated_at:TimestampValue};
const map=(r:Row):CharacterVisualRecord=>({id:r.id,projectId:r.project_id,characterId:r.character_id,characterName:r.character_name,versionNumber:r.version_number,status:r.status,faceAssetUri:r.face_asset_uri,costumeAssetUri:r.costume_asset_uri,fullbodyAssetUri:r.fullbody_asset_uri,inspaceAssetUri:r.inspace_asset_uri,propAssetUri:r.prop_asset_uri,continuityLock:r.continuity_lock_json,allowed:r.allowed_json,prohibited:r.prohibited_json,evidence:r.evidence_json,approvedBy:r.approved_by,approvedAt:toIsoString(r.approved_at),createdAt:toIsoString(r.created_at)!,updatedAt:toIsoString(r.updated_at)!});
export type CharacterVisualWrite={id:string;projectId:string;characterId:string;characterName:string;versionNumber:number;status?:VisualPrincipleStatus;faceAssetUri?:string|null;costumeAssetUri?:string|null;fullbodyAssetUri?:string|null;inspaceAssetUri?:string|null;propAssetUri?:string|null;continuityLock?:Record<string,unknown>;allowed?:unknown[];prohibited?:unknown[];evidence?:unknown[]};
export class CharacterVisualRepository{
  constructor(private readonly db:QueryExecutor){}
  async create(i:CharacterVisualWrite):Promise<CharacterVisualRecord>{const[r]=await this.db.query<Row>("INSERT INTO character_visual_bibles (id,project_id,character_id,character_name,version_number,status,face_asset_uri,costume_asset_uri,fullbody_asset_uri,inspace_asset_uri,prop_asset_uri,continuity_lock_json,allowed_json,prohibited_json,evidence_json) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12::jsonb,$13::jsonb,$14::jsonb,$15::jsonb) RETURNING *",[i.id,i.projectId,i.characterId,i.characterName,i.versionNumber,i.status??"candidate",i.faceAssetUri??null,i.costumeAssetUri??null,i.fullbodyAssetUri??null,i.inspaceAssetUri??null,i.propAssetUri??null,JSON.stringify(i.continuityLock??{}),JSON.stringify(i.allowed??[]),JSON.stringify(i.prohibited??[]),JSON.stringify(i.evidence??[])]);return map(r);}
  async get(id:string):Promise<CharacterVisualRecord|null>{const[r]=await this.db.query<Row>("SELECT * FROM character_visual_bibles WHERE id=$1",[id]);return r?map(r):null;}
  async linkScene(i:{bibleId:string;sceneId:string;characterId:string;linkReason?:string|null;evidence?:unknown[]}):Promise<void>{await this.db.query("INSERT INTO character_visual_scene_links (character_visual_bible_id,scene_id,character_id,link_reason,evidence_json) VALUES ($1,$2,$3,$4,$5::jsonb) ON CONFLICT DO NOTHING",[i.bibleId,i.sceneId,i.characterId,i.linkReason??null,JSON.stringify(i.evidence??[])]);}
  async listSceneLinks(bibleId:string):Promise<Array<{sceneId:string;characterId:string}>>{return(await this.db.query<{scene_id:string;character_id:string}>("SELECT scene_id,character_id FROM character_visual_scene_links WHERE character_visual_bible_id=$1 ORDER BY scene_id",[bibleId])).map(r=>({sceneId:r.scene_id,characterId:r.character_id}));}
}
