import type { QueryExecutor } from "./db";
import { ProjectRepository } from "./projectRepository";
import { toIsoString,type CascadeImpactRecord,type CharacterVisualRecord,type DecisionLineageRecord,type DecisionQuestionRecord,type PrincipleApprovalRecord,type ProjectRecord,type SceneRecord,type ShotRecord,type TimestampValue,type VisualPrincipleRecord,type VisualPrincipleVersionRecord,type VisualReferenceRecord } from "./types";

type Dated={createdAt:TimestampValue;updatedAt?:TimestampValue;approvedAt?:TimestampValue|null;withdrawnAt?:TimestampValue|null;evaluatedAt?:TimestampValue;appliedAt?:TimestampValue|null;decidedAt?:TimestampValue|null};
const dates=<T extends Dated>(row:T)=>({...row,createdAt:toIsoString(row.createdAt)!,...(row.updatedAt!==undefined?{updatedAt:toIsoString(row.updatedAt)!}:{}),...(row.approvedAt!==undefined?{approvedAt:toIsoString(row.approvedAt)}:{}),...(row.withdrawnAt!==undefined?{withdrawnAt:toIsoString(row.withdrawnAt)}:{}),...(row.evaluatedAt!==undefined?{evaluatedAt:toIsoString(row.evaluatedAt)!}:{}),...(row.appliedAt!==undefined?{appliedAt:toIsoString(row.appliedAt)}:{}),...(row.decidedAt!==undefined?{decidedAt:toIsoString(row.decidedAt)}:{})});
export type ReferenceWithLinks=VisualReferenceRecord&{sceneIds:string[]};
export type PrincipleWithCurrentVersion=VisualPrincipleRecord&{currentVersion:VisualPrincipleVersionRecord|null;approvals:PrincipleApprovalRecord[];sceneIds:string[];shotIds:string[]};
export type CharacterVisualWithLinks=CharacterVisualRecord&{sceneIds:string[]};
/** 승인·결정 주체는 이름 문자열이 아니라 참여자 ID 로 지정한다. */
export type ParticipantRecord={id:string;projectId:string;name:string;role:string;createdAt:string};
export type ProjectVisualWorkspaceReadModel={project:ProjectRecord;participants:ParticipantRecord[];scenes:SceneRecord[];shots:ShotRecord[];references:ReferenceWithLinks[];principles:PrincipleWithCurrentVersion[];decisionQuestions:DecisionQuestionRecord[];characterVisuals:CharacterVisualWithLinks[];cascadeImpacts:CascadeImpactRecord[];decisionLineage:DecisionLineageRecord[]};
export class WorkspaceReadModelRepository{
  constructor(private readonly db:QueryExecutor){}
  async get(projectId:string):Promise<ProjectVisualWorkspaceReadModel|null>{
    // 요청한 프로젝트가 없으면 null 을 반환한다. 다른 프로젝트 데이터로 대체하지 않는다.
    // 한때 "가장 오래된 프로젝트"를 대신 반환하는 폴백이 있었으나, 요청과 다른 작품의
    // 레퍼런스·원칙·캐릭터가 그대로 노출되면서 사용자가 그것이 잘못된 데이터임을 알 수
    // 없었다. 커밋 810a056(cross-meeting fallback 오염 제거)과 동일한 원칙이다 —
    // 한 요청 = 하나의 데이터 출처. 없으면 없다고 말한다.
    const project = await new ProjectRepository(this.db).getProject(projectId);
    if(!project)return null;
    const [participants,scenes,shots,references,referenceLinks,principles,versions,approvals,sceneLinks,shotLinks,questions,characters,characterLinks,impacts,lineage]=await Promise.all([
      this.db.query<any>('SELECT id,project_id "projectId",name,role,created_at "createdAt" FROM participants WHERE project_id=$1 ORDER BY role,name,id',[projectId]),
      this.db.query<any>('SELECT id,project_id "projectId",scene_number "sceneNumber",title,review_status "reviewStatus",created_at "createdAt",updated_at "updatedAt" FROM scenes WHERE project_id=$1 ORDER BY scene_number,id',[projectId]),
      this.db.query<any>('SELECT s.id,s.scene_id "sceneId",s.shot_number "shotNumber",s.title,s.status,s.generated_image_state "generatedImageState",s.image_uri "imageUri",s.approved_by "approvedBy",s.approved_at "approvedAt",s.created_at "createdAt",s.updated_at "updatedAt" FROM shots s JOIN scenes c ON c.id=s.scene_id WHERE c.project_id=$1 ORDER BY c.scene_number,s.shot_number,s.id',[projectId]),
      this.db.query<any>('SELECT id,project_id "projectId",title,source_method "sourceMethod",content_type "contentType",adoption_level "adoptionLevel",reference_image_state "referenceImageState",asset_uri "assetUri",take_json "take",drop_json "drop",responsible_role "responsibleRole",evidence_json "evidence",version_label "versionLabel",created_at "createdAt",updated_at "updatedAt" FROM visual_references WHERE project_id=$1 ORDER BY created_at,id',[projectId]),
      this.db.query<{referenceId:string;sceneId:string}>('SELECT l.reference_id "referenceId",l.scene_id "sceneId" FROM visual_reference_scene_links l JOIN visual_references r ON r.id=l.reference_id WHERE r.project_id=$1',[projectId]),
      this.db.query<any>('SELECT id,project_id "projectId",title,status,current_version_id "currentVersionId",created_at "createdAt",updated_at "updatedAt" FROM visual_principles WHERE project_id=$1 ORDER BY created_at,id',[projectId]),
      this.db.query<any>('SELECT v.id,v.principle_id "principleId",v.version_number "versionNumber",v.principle_text "principleText",v.rationale,v.change_summary "changeSummary",v.evidence_json "evidence",v.source_question_id "sourceQuestionId",v.content_hash "contentHash",v.created_by "createdBy",v.created_at "createdAt" FROM visual_principle_versions v JOIN visual_principles p ON p.id=v.principle_id WHERE p.project_id=$1 ORDER BY v.principle_id,v.version_number',[projectId]),
      this.db.query<any>('SELECT a.id,a.principle_version_id "principleVersionId",a.approver_id "approverId",a.role,a.status,a.evidence_uid "evidenceUid",a.approved_at "approvedAt",a.withdrawn_at "withdrawnAt",a.withdrawal_reason "withdrawalReason",a.created_at "createdAt" FROM visual_principle_approvals a JOIN visual_principle_versions v ON v.id=a.principle_version_id JOIN visual_principles p ON p.id=v.principle_id WHERE p.project_id=$1 ORDER BY a.approved_at,a.id',[projectId]),
      this.db.query<{versionId:string;sceneId:string}>('SELECT l.principle_version_id "versionId",l.scene_id "sceneId" FROM principle_scene_links l JOIN visual_principle_versions v ON v.id=l.principle_version_id JOIN visual_principles p ON p.id=v.principle_id WHERE p.project_id=$1',[projectId]),
      this.db.query<{versionId:string;shotId:string}>('SELECT l.principle_version_id "versionId",l.shot_id "shotId" FROM principle_shot_links l JOIN visual_principle_versions v ON v.id=l.principle_version_id JOIN visual_principles p ON p.id=v.principle_id WHERE p.project_id=$1',[projectId]),
      this.db.query<any>('SELECT id,project_id "projectId",question,context,state,priority,decided_option "decidedOption",decided_by "decidedBy",decided_at "decidedAt",evidence_json "evidence",created_at "createdAt",updated_at "updatedAt" FROM decision_questions WHERE project_id=$1 ORDER BY priority DESC,created_at,id',[projectId]),
      this.db.query<any>('SELECT id,project_id "projectId",character_id "characterId",character_name "characterName",version_number "versionNumber",status,face_asset_uri "faceAssetUri",costume_asset_uri "costumeAssetUri",fullbody_asset_uri "fullbodyAssetUri",inspace_asset_uri "inspaceAssetUri",prop_asset_uri "propAssetUri",continuity_lock_json "continuityLock",allowed_json "allowed",prohibited_json "prohibited",evidence_json "evidence",approved_by "approvedBy",approved_at "approvedAt",created_at "createdAt",updated_at "updatedAt" FROM character_visual_bibles WHERE project_id=$1 ORDER BY character_id,version_number',[projectId]),
      this.db.query<{bibleId:string;sceneId:string}>('SELECT l.character_visual_bible_id "bibleId",l.scene_id "sceneId" FROM character_visual_scene_links l JOIN character_visual_bibles b ON b.id=l.character_visual_bible_id WHERE b.project_id=$1',[projectId]),
      this.db.query<any>('SELECT id,project_id "projectId",principle_version_id "principleVersionId",change_type "changeType",target_type "targetType",target_id "targetId",impact_result "impactResult",target_new_status "targetNewStatus",reason,evaluated_at "evaluatedAt",applied_at "appliedAt" FROM cascade_impacts WHERE project_id=$1 ORDER BY evaluated_at,id',[projectId]),
      this.db.query<any>('SELECT id,project_id "projectId",source_type "sourceType",source_id "sourceId",relation,target_type "targetType",target_id "targetId",evidence_uid "evidenceUid",metadata_json "metadata",created_at "createdAt" FROM decision_lineage WHERE project_id=$1 ORDER BY created_at,id',[projectId]),
    ]);
    const normalizedVersions=versions.map(dates) as VisualPrincipleVersionRecord[];const normalizedApprovals=approvals.map(dates) as PrincipleApprovalRecord[];
    return{project,participants:participants.map(dates),scenes:scenes.map(dates),shots:shots.map(dates),references:references.map((r:any)=>({...dates(r),sceneIds:referenceLinks.filter(l=>l.referenceId===r.id).map(l=>l.sceneId)})),principles:principles.map((p:any)=>{const currentVersion=normalizedVersions.find(v=>v.id===p.currentVersionId)??null;return{...dates(p),currentVersion,approvals:currentVersion?normalizedApprovals.filter(a=>a.principleVersionId===currentVersion.id):[],sceneIds:currentVersion?sceneLinks.filter(l=>l.versionId===currentVersion.id).map(l=>l.sceneId):[],shotIds:currentVersion?shotLinks.filter(l=>l.versionId===currentVersion.id).map(l=>l.shotId):[]};}),decisionQuestions:questions.map(dates),characterVisuals:characters.map((c:any)=>({...dates(c),sceneIds:characterLinks.filter(l=>l.bibleId===c.id).map(l=>l.sceneId)})),cascadeImpacts:impacts.map(dates),decisionLineage:lineage.map(dates)};
  }
}
