import type { ReferenceImageState } from "../../domain/projectVisual";
import type { QueryExecutor } from "./db";
import { toIsoString,type TimestampValue,type VisualReferenceRecord } from "./types";

type ReferenceRow={id:string;project_id:string;title:string;source_method:string;content_type:string;adoption_level:VisualReferenceRecord["adoptionLevel"];reference_image_state:ReferenceImageState;asset_uri:string|null;take_json:unknown[];drop_json:unknown[];responsible_role:string;evidence_json:unknown[];version_label:string;created_at:TimestampValue;updated_at:TimestampValue};
const mapReference=(r:ReferenceRow):VisualReferenceRecord=>({id:r.id,projectId:r.project_id,title:r.title,sourceMethod:r.source_method,contentType:r.content_type,adoptionLevel:r.adoption_level,referenceImageState:r.reference_image_state,assetUri:r.asset_uri,take:r.take_json,drop:r.drop_json,responsibleRole:r.responsible_role,evidence:r.evidence_json,versionLabel:r.version_label,createdAt:toIsoString(r.created_at)!,updatedAt:toIsoString(r.updated_at)!});
export type ReferenceWrite={id:string;projectId:string;title:string;sourceMethod:string;contentType:string;adoptionLevel:VisualReferenceRecord["adoptionLevel"];referenceImageState:ReferenceImageState;assetUri?:string|null;take?:unknown[];drop?:unknown[];responsibleRole:string;evidence?:unknown[];versionLabel?:string};
export class ReferenceRepository{
  constructor(private readonly db:QueryExecutor){}
  async create(i:ReferenceWrite):Promise<VisualReferenceRecord>{const[r]=await this.db.query<ReferenceRow>("INSERT INTO visual_references (id,project_id,title,source_method,content_type,adoption_level,reference_image_state,asset_uri,take_json,drop_json,responsible_role,evidence_json,version_label) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb,$10::jsonb,$11,$12::jsonb,$13) RETURNING *",[i.id,i.projectId,i.title,i.sourceMethod,i.contentType,i.adoptionLevel,i.referenceImageState,i.assetUri??null,JSON.stringify(i.take??[]),JSON.stringify(i.drop??[]),i.responsibleRole,JSON.stringify(i.evidence??[]),i.versionLabel??"1.0"]);return mapReference(r);}
  async get(id:string):Promise<VisualReferenceRecord|null>{const[r]=await this.db.query<ReferenceRow>("SELECT * FROM visual_references WHERE id=$1",[id]);return r?mapReference(r):null;}
  async update(i:ReferenceWrite):Promise<VisualReferenceRecord>{const[r]=await this.db.query<ReferenceRow>("UPDATE visual_references SET title=$2,source_method=$3,content_type=$4,adoption_level=$5,reference_image_state=$6,asset_uri=$7,take_json=$8::jsonb,drop_json=$9::jsonb,responsible_role=$10,evidence_json=$11::jsonb,version_label=$12,updated_at=now() WHERE id=$1 AND project_id=$13 RETURNING *",[i.id,i.title,i.sourceMethod,i.contentType,i.adoptionLevel,i.referenceImageState,i.assetUri??null,JSON.stringify(i.take??[]),JSON.stringify(i.drop??[]),i.responsibleRole,JSON.stringify(i.evidence??[]),i.versionLabel??"1.0",i.projectId]);if(!r)throw new Error(`Reference not found: ${i.id}`);return mapReference(r);}
  async linkScene(referenceId:string,sceneId:string):Promise<void>{await this.db.query("INSERT INTO visual_reference_scene_links (reference_id,scene_id) VALUES ($1,$2) ON CONFLICT DO NOTHING",[referenceId,sceneId]);}
  async listSceneIds(referenceId:string):Promise<string[]>{return(await this.db.query<{scene_id:string}>("SELECT scene_id FROM visual_reference_scene_links WHERE reference_id=$1 ORDER BY scene_id",[referenceId])).map(r=>r.scene_id);}
}
