"use client";
import {useEffect,useState} from "react";
import type {getDecisionBoard} from "@/lib/meetingDecisions/store";
import type {CommandInput} from "@/lib/meetingDecisions/model";
import s from "./decisions.module.css";
import {ParticipantLinks} from "./ParticipantLinks";
import {InterpretationCard} from "./InterpretationCard";
type State=ReturnType<typeof getDecisionBoard>;
type Send=(command:CommandInput)=>Promise<boolean>;
const stanceLabel={agree:"진행 동의",agree_with_concerns:"우려를 남기고 진행 동의",disagree:"추가 논의 필요",uncertain:"판단 보류 · 확인 필요"};
export function DecisionBoard({meetingId,initialQuestionId,sourceHref}:{meetingId:string;initialQuestionId?:string;sourceHref?:string}){
 const [state,setState]=useState<State|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[selected,setSelected]=useState("");
 const [name,setName]=useState(""),[role,setRole]=useState(""),[question,setQuestion]=useState(""),[evidenceUid,setEvidenceUid]=useState("");
 const endpoint=`/api/meetings/${meetingId}/decisions`;
 async function refresh(){try{const r=await fetch(endpoint,{cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j.error);setState(j);}catch(e){setError((e as Error).message);}}
 useEffect(()=>{setSelected(initialQuestionId??new URLSearchParams(window.location.search).get("question")??"");void refresh();},[meetingId,initialQuestionId]);
 useEffect(()=>{const edited=(event:Event)=>{if((event as CustomEvent).detail?.meetingId===meetingId)void refresh();};window.addEventListener("nodam-source-edited",edited);return ()=>window.removeEventListener("nodam-source-edited",edited);},[meetingId]);
 const send:Send=async command=>{
  if(!state||busy)return false;setBusy(true);setError("");
  try{const r=await fetch(endpoint,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({revision:state.revision,command})});const j=await r.json();if(!r.ok){if(r.status===409)await refresh();throw new Error(j.error);}setState(j);return true;}catch(e){setError((e as Error).message);return false;}finally{setBusy(false);}
 };
 function download(){if(!state)return;const url=URL.createObjectURL(new Blob([JSON.stringify({meetingId,exportedAt:new Date().toISOString(),...state},null,2)],{type:"application/json"}));const a=document.createElement("a");a.href=url;a.download=`동상이몽-결정기록-${meetingId}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 if(!state)return <section className={s.card}><h1>함께 확인하고 결정하기</h1><p role="status">{error||"회의 기록을 불러오는 중입니다."}</p><button onClick={()=>void refresh()}>다시 불러오기</button></section>;
 const active=state.questions.find(q=>q.id===selected)??state.questions[0];
 const source=state.evidence.find(e=>e.uid===evidenceUid)??state.evidence[0];
 return <div className={s.page}>
  <header className={s.heading}><div><span className={s.eyebrow}>공동 의사결정</span><h1>같은 뜻인지 확인하고, 다음 일을 정합니다.</h1><p>원문 근거 → 참가자의 이해 → 결정안과 실행 과제</p></div><div className={s.actions}><button onClick={()=>void refresh()} disabled={busy}>새 기록 불러오기</button><button onClick={download}>결정·평가 기록 내려받기</button></div></header>
  {state.goal&&<section className={s.card}><span className={s.eyebrow}>고정된 회의 목적</span><p>{state.goal}</p></section>}
  <p className={s.notice}><strong>개인 링크 응답과 진행자의 대리 기록</strong>을 구분해 보관합니다. 개인 링크는 실명 인증된 투표가 아닙니다. 미응답은 동의가 아니며, 결정안을 고치면 다시 확인해야 합니다.</p>
  {active?.sourceChanged&&<p role="alert" className={s.notice}>{active.confirmedAt?"확정 당시 기록은 보존되어 있습니다. 이후 근거 발언·화자가 수정되어 현재 내용과 다를 수 있습니다.":"근거 발언·화자가 수정되었습니다. 다시 분석한 후보로 확인해 주세요."}</p>}
  {error&&<p className={s.error} role="alert">{error}</p>}
  <section className={s.card}><h2>참가자와 역할</h2><div className={s.people}>{state.participants.map(p=><span key={p.id} className={s.person}><strong>{p.name}</strong>{p.role&&` · ${p.role}`}</span>)}{!state.participants.length&&<p className={s.muted}>실명 또는 서로 구분할 이름을 직접 등록해 주세요.</p>}</div><form className={s.inline} onSubmit={async e=>{e.preventDefault();if(await send({action:"participant",name,role})){setName("");setRole("");}}}><label>참가자 이름<input disabled={busy} value={name} onChange={e=>setName(e.target.value)} maxLength={80} required/></label><label>역할 · 선택<input disabled={busy} value={role} onChange={e=>setRole(e.target.value)} maxLength={100}/></label><button disabled={busy}>참가자 등록</button></form></section>
  <section className={s.card}><ParticipantLinks meetingId={meetingId} participants={state.participants}/></section>
  <details className={s.card}><summary>원문에서 확인 안건 직접 등록</summary><form onSubmit={async e=>{e.preventDefault();if(source&&await send({action:"question",question,evidence:[{uid:source.uid,quote:source.text.slice(0,5000)}]}))setQuestion("");}}><label>확인할 질문<textarea disabled={busy} aria-label="확인할 질문" value={question} onChange={e=>setQuestion(e.target.value)} maxLength={500} required placeholder="예: ‘간단하게’가 비용을 줄이자는 뜻인지, 시간을 줄이자는 뜻인지 확인할까요?"/></label><label>원문 근거<select disabled={busy} value={source?.uid??""} onChange={e=>setEvidenceUid(e.target.value)} required><option value="" disabled>발언 선택</option>{state.evidence.map(e=><option key={e.uid} value={e.uid}>{e.uid} · {e.speaker} · {e.text.slice(0,50)}</option>)}</select></label>{source&&<blockquote>{source.text}</blockquote>}<button disabled={busy||!source}>확인 안건 등록</button></form><p className={s.muted}>실시간 검토의 ‘함께 확인하기’ 버튼으로 AI 후보를 원문과 함께 가져올 수도 있습니다.</p></details>
  <nav className={s.tabs} aria-label="확인 안건">{state.questions.map((q,i)=><button key={q.id} onClick={()=>setSelected(q.id)} aria-pressed={active?.id===q.id}>{i+1}. {q.confirmedAt?"확인 완료":"확인 중"} · {q.question.slice(0,35)}</button>)}</nav>
  {!active?<section className={s.card}><h2>등록된 확인 안건이 없습니다.</h2><p>AI 검토 후보를 가져오거나 원문에서 질문을 등록하세요. 안건이 없다는 사실만으로 전원이 합의했다고 판단하지 않습니다.</p></section>:<QuestionEditor key={active.id} board={state} question={active} send={send} busy={busy} meetingId={meetingId} sourceHref={sourceHref}/>}
  <section className={s.card}><h2>실행 과제</h2>{state.questions.filter(q=>q.confirmedAt&&q.task).length?state.questions.filter(q=>q.confirmedAt&&q.task).map(q=><article className={s.task} key={q.id}><strong>{q.proposal}</strong><p>담당 {q.participantsAtConfirmation.find(p=>p.id===q.task?.ownerId)?.name??"미정"} · 기한 {q.task!.dueDate??"미정"}</p><p>완료 기준: {q.task!.criteria}</p>{q.comparison?.synthesis&&<><p>함께 확인한 조건: {q.comparison.synthesis.sharedConditions}</p><p>남은 해석 차이·처리 방향: {q.comparison.synthesis.remainingDifferences||"기록된 차이 없음"}</p></>}{q.responses.filter(r=>r.concern).map(r=><p key={r.participantId}><strong>남긴 우려 · {q.participantsAtConfirmation.find(p=>p.id===r.participantId)?.name}:</strong> {r.concern}</p>)}<button disabled={busy} onClick={()=>void send({action:"task",questionId:q.id,done:!q.task!.done})}>{q.task!.done?"완료됨 · 다시 진행으로":"실행 완료로 기록"}</button></article>):<p className={s.muted}>공동 확인을 마친 결정만 실행 과제로 표시됩니다.</p>}</section>
  <details className={s.card}><summary>변경 기록 · 현재 버전 {state.revision}</summary><p className={s.muted}>기록에는 참가자 입력, 제안 수정, 응답과 확인 완료 시점이 남습니다. 내보내기에는 최근 100개 변경 내역이 포함됩니다.</p>{state.history.map((h:any)=><p key={h.revision}>#{h.revision} · {h.created_at} · {({comparison:"해석 비교 대상 변경",interpretation:"본인 해석 기록",synthesis:"해석 비교 정리",participant:"참가자 등록",question:"안건 등록",import:"AI 후보 가져오기",import_analysis:"회의 전체 분석 후보 가져오기",proposal:"결정안 변경",response:"확인 내용 기록",confirm:"공동 확인 완료",task:"실행 상태 변경",feedback:"검토 평가"} as Record<string,string>)[h.action]??h.action}</p>)}</details>
 </div>;
}
function QuestionEditor({board,question:q,send,busy,meetingId,sourceHref}:{board:State;question:State["questions"][number];send:Send;busy:boolean;meetingId:string;sourceHref?:string}){
 const [proposal,setProposal]=useState(q.proposal),[owner,setOwner]=useState(q.task?.ownerId??board.participants[0]?.id??""),[due,setDue]=useState(q.task?.dueDate??""),[criteria,setCriteria]=useState(q.task?.criteria??"");
 const [person,setPerson]=useState(board.participants[0]?.id??""),[stance,setStance]=useState<keyof typeof stanceLabel>("uncertain"),[understanding,setUnderstanding]=useState(""),[concern,setConcern]=useState("");
 const [verdict,setVerdict]=useState<"valid"|"false_alarm"|"uncertain">(q.feedback?.verdict??"uncertain"),[reason,setReason]=useState(q.feedback?.reason??"");
 useEffect(()=>{setUnderstanding("");setConcern("");setStance("uncertain");},[q.proposalRevision]);
 return <section><h2>{q.question}</h2><InterpretationCard question={q} participants={board.participants} busy={busy} send={send} onUseConditions={value=>{setProposal(value);document.getElementById("decision-proposal")?.focus();}}/><div className={s.columns}>
  <article className={s.card}><span className={s.eyebrow}>01 · 원문 근거</span><h3>실제로 한 말</h3><p className={s.muted}>{q.source||q.analysisSource?"AI가 제안한 확인 후보 · 사람 검토 필요":"사람이 등록한 확인 질문"}</p>{q.evidence.map((e,i)=><blockquote key={i}><a href={`${sourceHref??`/m/${meetingId}?tab=transcript`}#u_${e.uid}`}>{e.uid}</a><p>{e.quote}</p></blockquote>)}<details><summary>이 후보의 유효성 평가</summary><form onSubmit={async e=>{e.preventDefault();await send({action:"feedback",questionId:q.id,verdict,reason});}}><label>평가<select disabled={busy} aria-label="평가" value={verdict} onChange={e=>setVerdict(e.target.value as typeof verdict)}><option value="uncertain">판단 유보</option><option value="valid">확인이 필요한 후보</option><option value="false_alarm">오경보</option></select></label><label>판단 근거<textarea disabled={busy} aria-label="판단 근거" value={reason} onChange={e=>setReason(e.target.value)} maxLength={1000} required/></label><button disabled={busy}>평가 저장</button></form>{q.feedback&&<p>저장된 평가: {q.feedback.verdict} · {q.feedback.reason}</p>}</details></article>
  <article className={s.card}><span className={s.eyebrow}>02 · 참가자의 이해</span><h3>어떻게 이해했고, 진행에 동의하나요?</h3><p className={s.muted}>생각이 완전히 같을 필요는 없습니다. 이해한 내용과 진행 의사를 구분하고, 남은 우려를 기록합니다.</p>{(q.confirmedAt?q.participantsAtConfirmation:board.participants).map(p=>{const r=q.responses.find(r=>r.participantId===p.id&&r.proposalRevision===q.proposalRevision);return <div className={s.response} key={p.id}><strong>{p.name}</strong><span className={s.status}>{r?stanceLabel[r.stance]:"미응답"}</span>{r&&<small>{r.recordedVia==="personal_link"?"개인 초대 링크로 직접 응답":"진행자가 확인 내용 기록"}</small>}<p>{r?.understanding??"아직 확인 내용이 기록되지 않았습니다."}</p>{r?.concern&&<p><strong>남긴 우려:</strong> {r.concern}</p>}</div>;})}{!q.confirmedAt&&<form onSubmit={async e=>{e.preventDefault();if(await send({action:"response",questionId:q.id,participantId:person,stance,understanding,concern:stance==="agree_with_concerns"?concern:""})){setUnderstanding("");setConcern("");setStance("uncertain");}}}><label>응답한 참가자<select disabled={busy} aria-label="응답한 참가자" value={person} onChange={e=>setPerson(e.target.value)} required><option value="" disabled>참가자 선택</option>{board.participants.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>확인 상태<select disabled={busy} aria-label="확인 상태" value={stance} onChange={e=>setStance(e.target.value as typeof stance)}>{Object.entries(stanceLabel).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>본인이 이해한 내용<textarea disabled={busy} aria-label="본인이 이해한 내용" value={understanding} onChange={e=>setUnderstanding(e.target.value)} maxLength={1000} required placeholder="어떤 조건으로 무엇을 하자는 뜻인지 기록합니다."/></label>{stance==="agree_with_concerns"&&<label>남기는 우려<textarea disabled={busy} aria-label="남기는 우려" value={concern} onChange={e=>setConcern(e.target.value)} maxLength={1000} required placeholder="진행에는 동의하지만 어떤 우려가 남는지 기록합니다. 결정 확정 후에도 보존됩니다."/></label>}<button disabled={busy||!q.proposal}>확인 내용 기록</button></form>}</article>
  <article className={s.card}><span className={s.eyebrow}>03 · 결정과 실행</span><h3>{q.confirmedAt?"공동 확인 완료":"결정안 작성"}</h3>{q.confirmedAt?<><p>{q.proposal}</p><p>기한 {q.task?.dueDate??"미정"}</p><p>완료 기준: {q.task?.criteria}</p><p className={s.muted}>{q.confirmedAt} · 진행자가 기록한 전원의 진행 동의 · 남은 우려 포함</p></>:<><form onSubmit={async e=>{e.preventDefault();await send({action:"proposal",questionId:q.id,proposal,ownerId:owner,dueDate:due||null,criteria});}}><label>결정안<textarea disabled={busy} id="decision-proposal" aria-label="결정안" value={proposal} onChange={e=>setProposal(e.target.value)} maxLength={2000} required/></label><label>실행 담당자<select disabled={busy} aria-label="실행 담당자" value={owner} onChange={e=>setOwner(e.target.value)} required><option value="" disabled>담당자 선택</option>{board.participants.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>실행 기한 · 미정 가능<input disabled={busy} type="date" value={due} onChange={e=>setDue(e.target.value)}/></label><label>완료 기준<textarea disabled={busy} aria-label="완료 기준" value={criteria} onChange={e=>setCriteria(e.target.value)} maxLength={1000} required/></label><button disabled={busy}>결정안 저장 · 다시 확인받기</button></form><p className={s.muted}>결정안, 담당자, 기한 또는 완료 기준을 저장하면 기존 동의 기록을 초기화합니다.</p><ul className={s.blockers}>{q.blockers.map((b,i)=><li key={i}>{b}</li>)}</ul><button className={s.primary} disabled={busy||q.blockers.length>0} onClick={()=>void send({action:"confirm",questionId:q.id})}>공동 확인 완료로 기록</button></>}</article>
 </div></section>;
}
